// Auto-generated from DotGUI/select.html + pages/game-pages (listed flag = visible in catalog).
// slug: pages/game-pages/<slug>.html | key: data-title filter key | label: tile alt text
// embed: local 'game-embeds/x.html' path or absolute external URL.

export const games = [
  { slug: '1v1lol', title: '1v1.lol', key: '1v1.lol', label: '1v1.lol', img: 'media/buttons/1v1.jpeg', embed: 'game-embeds/1v1lol.html', external: false, listed: true },
  { slug: 'agario', title: 'AgarIO', key: 'AgarIO', label: 'AgarIO', img: '', embed: 'game-embeds/agario.html', external: false, listed: false },
  { slug: 'amongus', title: 'Among Us', key: 'Among Us', label: 'Among Us', img: 'media/buttons/Among_Us.webp', embed: 'game-embeds/amongus.html', external: false, listed: true },
  { slug: 'awesome', title: 'Awesome Tanks', key: 'Awesome Tanks', label: 'Awesome Tanks', img: '', embed: 'game-embeds/awesome.html', external: false, listed: false },
  { slug: 'badtimesimulator', title: 'Bad Time Simulator', key: 'Bad Time Simulator', label: 'Bad Time Simulator', img: 'media/buttons/badtime.webp', embed: 'game-embeds/badtime.html', external: false, listed: true },
  { slug: 'baldibasics', title: 'Baldi\'s Basics', key: 'Baldi\'s Basics', label: 'Baldi\'s Basics', img: 'media/buttons/baldi.png', embed: 'https://definitelynotblocked-three.vercel.app/games/baldisbasics/index.html', external: true, listed: true },
  { slug: 'basebros', title: 'Baseball Bros', key: 'Baseball Bros', label: 'Baseball Bros', img: '', embed: 'game-embeds/basebros.html', external: false, listed: false },
  { slug: 'basketbros', title: 'Basketbros', key: 'Basketbros', label: 'Basketbros', img: '', embed: 'game-embeds/basketbros.html', external: false, listed: false },
  { slug: 'basketrandom', title: 'Basket Random', key: 'Basket Random', label: 'Basket Random', img: 'media/buttons/basket.png', embed: 'https://definitelynotblocked-three.vercel.app/games/basketrandom/index.html', external: true, listed: true },
  { slug: 'basketstars', title: 'Basket Stars', key: 'Basket Stars', label: 'Basket Stars', img: '', embed: 'game-embeds/basketstars.html', external: false, listed: false },
  { slug: 'binding', title: 'Binding Of Issac: Wrath of the Lamb', key: 'Binding Of Issac: Wrath of the Lamb', label: 'Binding Of Issac: Wrath of the Lamb', img: '', embed: 'game-embeds/bind.html', external: false, listed: false },
  { slug: 'bitlife', title: 'Bitlife', key: 'Bitlife', label: 'Bitlife', img: 'media/buttons/bitlife.png', embed: 'game-embeds/bitlife.html', external: false, listed: true },
  { slug: 'blockblast', title: 'Block Blast', key: 'Block Blast', label: 'Block Blast', img: '', embed: 'https://blocksss-one.vercel.app/', external: true, listed: false },
  { slug: 'boxingrandom', title: 'Boxing Random', key: 'Boxing Random', label: 'Boxing Random', img: 'media/buttons/boxing.png', embed: 'game-embeds/boxingrandom.html', external: false, listed: true },
  { slug: 'celeste', title: 'Celeste', key: 'Celeste', label: 'Celeste', img: 'media/buttons/celeste.jpg', embed: 'game-embeds/celeste.html', external: false, listed: true },
  { slug: 'clash', title: 'Clash of Vikings', key: 'Clash of Vikings', label: 'Clash of Vikings', img: '', embed: 'game-embeds/clash.html', external: false, listed: false },
  { slug: 'codmw4', title: 'Call of Duty 4 - Modern Warfare', key: 'Call of Duty 4 - Modern Warfare', label: 'Call of Duty 4 - Modern Warfare', img: '', embed: 'game-embeds/codmw4.html', external: false, listed: false },
  { slug: 'cookieclicker', title: 'Cookie Clicker', key: 'Cookie Clicker', label: 'Cookie Clicker', img: 'media/buttons/cookieclicker.jpg', embed: 'game-embeds/cookie.html', external: false, listed: true },
  { slug: 'crossyroads', title: 'Crossy Roads', key: 'Crossy Roads', label: 'Crossy Roads', img: 'media/buttons/Crossy_Road_icon.jpeg', embed: 'game-embeds/crossyroads.html', external: false, listed: true },
  { slug: 'csgoclicker', title: 'CSGO Clicker', key: 'CSGO Clicker', label: 'CSGO Clicker', img: 'media/buttons/csgo.jpeg', embed: 'game-embeds/csgo.html', external: false, listed: true },
  { slug: 'deltarune', title: 'Deltarune', key: 'Deltarune', label: 'Deltarune', img: 'media/buttons/deltarune.webp', embed: 'game-embeds/deltarune.html', external: false, listed: true },
  { slug: 'doom', title: 'Doom', key: 'Doom', label: 'Doom', img: 'media/buttons/doom.jpeg', embed: 'game-embeds/doom.html', external: false, listed: true },
  { slug: 'drifthunters', title: 'Drift Hunters', key: 'Drift Hunters', label: 'Drift Hunters', img: 'media/buttons/drifthunters.jpeg', embed: 'game-embeds/drifthunters.html', external: false, listed: true },
  { slug: 'dynablocks', title: 'Dynablocks', key: 'Dynablocks', label: 'Dynablocks', img: '', embed: 'https://fvuiaosvhsfasjdfsagp.netlify.app/apps/godoblocks/', external: true, listed: false },
  { slug: 'eaglercraft122', title: 'EaglerCraft 1.12.2', key: 'Eaglercraft 1.12.2', label: 'Eaglercraft 1.12.2', img: 'media/buttons/eagler.png', embed: 'game-embeds/eaglercraft122.html', external: false, listed: true },
  { slug: 'eaglercraft152', title: 'EaglerCraft 1.5.2', key: 'EaglerCraft 1.5.2', label: 'EaglerCraft 1.5.2', img: '', embed: 'game-embeds/eaglercraft152.html', external: false, listed: false },
  { slug: 'fancypantsadventure', title: 'Fancy Pants Adventure', key: 'Fancy Pants Adventure', label: 'Fancy Pants Adventure', img: 'media/buttons/fancy.png', embed: 'game-embeds/fancypantsadventure.html', external: false, listed: true },
  { slug: 'fifa11', title: 'FIFA 11', key: 'Fifa 11', label: 'Fifa 11', img: 'media/buttons/fifa11.jpg', embed: 'game-embeds/fifa11.html', external: false, listed: true },
  { slug: 'fnaf', title: 'Fnaf', key: 'Fnaf', label: 'Fnaf', img: '', embed: 'game-embeds/fnaf.html', external: false, listed: false },
  { slug: 'fnaf2', title: 'Fnaf 2', key: 'Fnaf 2', label: 'Fnaf 2', img: '', embed: 'game-embeds/fnaf2.html', external: false, listed: false },
  { slug: 'fnaf3', title: 'Fnaf 3', key: 'Fnaf 3', label: 'Fnaf 3', img: '', embed: 'game-embeds/fnaf3.html', external: false, listed: false },
  { slug: 'fnaf4', title: 'Fnaf 4', key: 'Fnaf 4', label: 'Fnaf 4', img: '', embed: 'game-embeds/fnaf4.html', external: false, listed: false },
  { slug: 'fnf', title: 'Friday Night Funkin', key: 'FNF', label: 'Friday Night Funkin', img: 'media/buttons/fnf.webp', embed: 'game-embeds/fnf.html', external: false, listed: true },
  { slug: 'footbros', title: 'Football Bros', key: 'Football Bros', label: 'Football Bros', img: '', embed: 'game-embeds/footbros.html', external: false, listed: false },
  { slug: 'fruitninja', title: 'Fruit Ninja', key: 'Fruit Ninja', label: 'Fruit Ninja', img: 'media/buttons/fruit.webp', embed: 'game-embeds/fruitninja.html', external: false, listed: true },
  { slug: 'funnyshooter2', title: 'Funny Shooter 2', key: 'Funny Shooter 2', label: 'Funny Shooter 2', img: 'media/buttons/funny-shooter-2.jpg', embed: 'game-embeds/funnyshooter2.html', external: false, listed: true },
  { slug: 'geometrydash', title: 'Geometry Dash', key: 'Geometry Dash', label: 'Geometry Dash', img: 'media/buttons/geometry.png', embed: 'game-embeds/geometrydash.html', external: false, listed: true },
  { slug: 'geometrydashdemake', title: 'Geometry Dash Demake', key: 'Geometry Dash Demake', label: 'Geometry Dash Demake', img: 'media/buttons/geodashdemake.png', embed: 'game-embeds/geodash_gba_port/index.html', external: false, listed: true },
  { slug: 'gladdihoppers', title: 'Gladdihoppers', key: 'Gladdihoppers', label: 'Gladdihoppers', img: '', embed: 'game-embeds/gladd.html', external: false, listed: false },
  { slug: 'granny', title: 'Granny', key: 'Granny', label: 'Granny', img: '', embed: 'game-embeds/granny.html', external: false, listed: false },
  { slug: 'granny2', title: 'Granny 2', key: 'Granny 2', label: 'Granny 2', img: '', embed: 'game-embeds/granny2.html', external: false, listed: false },
  { slug: 'hazard', title: 'House of Hazards', key: 'House of Hazards', label: 'House of Hazards', img: '', embed: 'game-embeds/hazard.html', external: false, listed: false },
  { slug: 'hollow', title: 'Hollow Knight', key: 'Hollow Knight', label: 'Hollow Knight', img: '', embed: 'game-embeds/hollow.html', external: false, listed: false },
  { slug: 'icedodo', title: 'Ice Dodo', key: 'Ice Dodo', label: 'Ice Dodo', img: '', embed: 'game-embeds/icedodo.html', external: false, listed: false },
  { slug: 'jet', title: 'Jetpack Joyride', key: 'Jetpack Joyride', label: 'Jetpack Joyride', img: 'media/buttons/jetpack.jpg', embed: 'game-embeds/jet.html', external: false, listed: true },
  { slug: 'karl', title: 'Karlson', key: 'Karlson', label: 'Karlson', img: 'media/buttons/karl.jpg', embed: 'game-embeds/karl.html', external: false, listed: true },
  { slug: 'kinder', title: 'Kindergarten', key: 'Kindergarten', label: 'Kindergarten', img: '', embed: 'game-embeds/kinder.html', external: false, listed: false },
  { slug: 'kinder2', title: 'Kindergarten 2', key: 'Kindergarten 2', label: 'Kindergarten 2', img: '', embed: 'game-embeds/kinder2.html', external: false, listed: false },
  { slug: 'kinder3', title: 'Kindergarten 3', key: 'Kindergarten 3', label: 'Kindergarten 3', img: '', embed: 'game-embeds/kinder3.html', external: false, listed: false },
  { slug: 'linerider', title: 'Line Rider', key: 'Line Rider', label: 'Line Rider', img: 'media/buttons/linerider.png', embed: 'game-embeds/linerider.html', external: false, listed: true },
  { slug: 'mariocombat', title: 'Mario Combat', key: 'Mario Combat', label: 'Mario Combat', img: 'media/buttons/mariocombat.png', embed: 'game-embeds/mariocombat.html', external: false, listed: true },
  { slug: 'mariokart64', title: 'Mario Kart 64', key: 'Mario Kart 64', label: 'Mario Kart 64', img: 'media/buttons/mariokart.jpeg', embed: 'game-embeds/mariokart64.html', external: false, listed: true },
  { slug: 'metal', title: 'Metal Gear Solid', key: 'Metal Gear Solid', label: 'Metal Gear Solid', img: 'media/buttons/metal.jpg', embed: 'game-embeds/metal.html', external: false, listed: true },
  { slug: 'metroidfusion', title: 'Metroid Fusion', key: 'Metroid Fusion', label: 'Metroid Fusion', img: 'media/buttons/metroid.jpg', embed: 'game-embeds/metroidfusion.html', external: false, listed: true },
  { slug: 'motox3m', title: 'Moto X3M', key: 'MotoX3M', label: 'MotoX3M', img: 'media/buttons/motox3m.png', embed: 'game-embeds/motox3m.html', external: false, listed: true },
  { slug: 'ngon', title: 'N-Gon', key: 'N-Gon', label: 'N-Gon', img: 'media/buttons/ngon.jpeg', embed: 'https://efbklgwnrveklbj.vercel.app/', external: true, listed: true },
  { slug: 'nutsnbolts', title: 'Nuts and Bolts Screwing Puzzle', key: 'Nuts', label: 'Nuts', img: 'media/buttons/nuts.png', embed: 'game-embeds/nutsnbolts.html', external: false, listed: true },
  { slug: 'oblivioneve', title: 'Oblivion Eve', key: 'Oblivion Eve', label: 'Oblivion Eve', img: '', embed: 'game-embeds/oblivoneve.html', external: false, listed: false },
  { slug: 'ocarina', title: 'The Legend of Zelda: Ocarina of Time', key: 'The Legend of Zelda: Ocarina of Time', label: 'The Legend of Zelda: Ocarina of Time', img: 'media/buttons/ocorina.jpg', embed: 'game-embeds/ocarina.html', external: false, listed: true },
  { slug: 'omori', title: 'Omori', key: 'Omori', label: 'Omori', img: 'media/buttons/omori.jpeg', embed: 'game-embeds/omori.html', external: false, listed: true },
  { slug: 'oneshot', title: 'Oneshot', key: 'Oneshot', label: 'Oneshot', img: '', embed: 'game-embeds/oneshot.html', external: false, listed: false },
  { slug: 'ovo', title: 'OvO', key: 'OvO', label: 'OvO', img: 'media/buttons/ovo.png', embed: 'game-embeds/ovo.html', external: false, listed: true },
  { slug: 'ovo2', title: 'OvO 2', key: 'OvO 2', label: 'OvO 2', img: 'media/buttons/ovo2.webp', embed: 'game-embeds/ovo2.html', external: false, listed: true },
  { slug: 'paperio', title: 'Paper IO', key: 'Paper IO', label: 'Paper IO', img: '', embed: 'game-embeds/paperio.html', external: false, listed: false },
  { slug: 'pokemonemerald', title: 'Pokemon Emerald', key: 'Pokemon', label: 'Pokemon Emerald', img: 'media/buttons/emerald.jpg', embed: 'game-embeds/pokemonemerald.html', external: false, listed: true },
  { slug: 'pokemonemeraldrg', title: 'Pokemon Emerald: Rouge', key: 'Pokemon', label: 'Pokemon Emerald Rogue', img: 'media/buttons/rouge.png', embed: 'game-embeds/pokemonemeraldrg.html', external: false, listed: true },
  { slug: 'pokemonfirered', title: 'Pokemon Fire Red', key: 'Pokemon', label: 'Pokemon Fire Red', img: 'media/buttons/pokefire.jpg', embed: 'game-embeds/pokemonfirered.html', external: false, listed: true },
  { slug: 'pokemonleafgreen', title: 'Pokemon Leaf Green', key: 'Pokemon', label: 'Pokemon Leaf Green', img: 'media/buttons/leafgreen.jpg', embed: 'game-embeds/pokemonleafgreen.html', external: false, listed: true },
  { slug: 'pokemonruby', title: 'Pokemon Ruby', key: 'Pokemon', label: 'Pokemon Ruby', img: 'media/buttons/ruby.png', embed: 'game-embeds/pokemonruby.html', external: false, listed: true },
  { slug: 'pokemonstadium', title: 'Pokemon Stadium', key: 'Pokemon', label: 'Pokemon Stadium', img: 'media/buttons/stadium.webp', embed: 'game-embeds/pokemonstadium.html', external: false, listed: true },
  { slug: 'pokemonunbound', title: 'Pokemon Unbound', key: 'Pokemon', label: 'Pokemon Unbound', img: 'media/buttons/pokeunbound.webp', embed: 'game-embeds/pokemonunbound.html', external: false, listed: true },
  { slug: 'redball', title: 'Red Ball 4', key: 'Red Ball', label: 'Red Ball', img: 'media/buttons/redball.webp', embed: 'game-embeds/redball.html', external: false, listed: true },
  { slug: 'repo', title: 'R.E.P.O', key: 'R.E.P.O', label: 'R.E.P.O', img: '', embed: 'game-embeds/repo.html', external: false, listed: false },
  { slug: 'retrobowl', title: 'Retro Bowl', key: 'Retro Bowl', label: 'Retro Bowl', img: 'media/buttons/unnamed.png', embed: 'game-embeds/retrobowl.html', external: false, listed: true },
  { slug: 'retrobowlcollege', title: 'Retro Bowl College', key: 'Retro Bowl College', label: 'Retro Bowl College', img: '', embed: 'game-embeds/retrobowlcollege.html', external: false, listed: false },
  { slug: 'riddleschool', title: 'Riddle School', key: 'Riddle School', label: 'Riddle School', img: 'media/buttons/riddle.jpeg', embed: 'game-embeds/riddleschool.html', external: false, listed: true },
  { slug: 'rooftopsnipers', title: 'Rooftop Snipers', key: 'Rooftop Snipers', label: 'Rooftop Snipers', img: 'media/buttons/rooftop.png', embed: 'game-embeds/rooftopsnipers.html', external: false, listed: true },
  { slug: 'rooftopsnipers2', title: 'Rooftop Snipers 2', key: 'Rooftop Snipers', label: 'Rooftop Snipers 2', img: 'media/buttons/rooftop2.jpeg', embed: 'game-embeds/rooftopsnipers2.html', external: false, listed: true },
  { slug: 'silentps1', title: 'Silent Hill PS1', key: 'Silent Hill PS1', label: 'Silent Hill PS1', img: '', embed: 'game-embeds/silent.html', external: false, listed: false },
  { slug: 'silksong', title: 'Hollow Knight: Silksong DEMAKE', key: 'Hollow Knight: Silksong DEMAKE', label: 'Hollow Knight: Silksong DEMAKE', img: '', embed: 'game-embeds/silksong.html', external: false, listed: false },
  { slug: 'slope', title: 'Slope', key: 'Slope', label: 'Slope', img: 'media/buttons/slope.jpg', embed: 'https://definitelynotblocked-three.vercel.app/games/slope/index.html', external: true, listed: true },
  { slug: 'slope2player', title: 'Slope 2 Player', key: 'Slope 2 Player', label: 'Slope 2 Player', img: 'media/buttons/slope2.png', embed: 'https://definitelynotblocked-three.vercel.app/games/slope2/index.html', external: true, listed: true },
  { slug: 'slopeplus', title: 'Slope Plus', key: 'Slope Plus', label: 'Slope Plus', img: 'media/buttons/slopeplus.png', embed: 'game-embeds/slopeplus.html', external: false, listed: true },
  { slug: 'snowbattle', title: 'Snowbattle.io', key: 'Snowbattleio', label: 'Snow Battle IO', img: 'media/buttons/snowbattle.jpg', embed: 'game-embeds/snow.html', external: false, listed: true },
  { slug: 'snowrider', title: 'Snow Rider 3D', key: 'Snow Rider 3D', label: 'Snow Rider 3D', img: '', embed: 'game-embeds/snowrider.html', external: false, listed: false },
  { slug: 'soccerrandom', title: 'Soccer Random', key: 'Soccer Random', label: 'Soccer Random', img: 'media/buttons/soccer.png', embed: 'https://definitelynotblocked-three.vercel.app/games/soccerrandom/index.html', external: true, listed: true },
  { slug: 'soccerskills', title: 'Soccer Skills | World Cup', key: 'Soccer Skills World Cup', label: 'Soccer Skills World Cup', img: 'media/buttons/cupofworld.png', embed: 'https://sipragio06.github.io/soccer-skills-game/', external: true, listed: true },
  { slug: 'sonicthehedgehog', title: 'Sonic the Hedgehog for the Sega Genisis', key: 'Sonic', label: 'Sonic the Hedgehog', img: 'media/buttons/sonic.jpeg', embed: 'game-embeds/sonicthehedgehog.html', external: false, listed: true },
  { slug: 'stickslasher', title: 'Stick Slasher', key: 'Stick Slasher', label: 'Stick Slasher', img: '', embed: 'https://ugs-assets.vercel.app/stick%20slasher/index.html', external: true, listed: false },
  { slug: 'subwaysurfersmiami', title: 'Subway Surfers: Miami', key: 'Subway Surfers', label: 'Subway Surfers: Miami', img: 'media/buttons/subwaymiami.webp', embed: 'game-embeds/subwaysurfersmiami.html', external: false, listed: true },
  { slug: 'subwaysurferswinterholiday', title: 'Subway Surfers: Winter Holiday', key: 'Subway Surfers', label: 'Subway Surfers: Winter Holiday', img: 'media/buttons/wintersurf.webp', embed: 'game-embeds/subwaysurferswinterholiday.html', external: false, listed: true },
  { slug: 'supermario64', title: 'Super Mario 64', key: 'Super Mario 64', label: 'Super Mario 64', img: '', embed: 'game-embeds/supermario64.html', external: false, listed: false },
  { slug: 'supermariobros', title: 'Super Mario Bros', key: 'Super Mario Bros', label: 'Super Mario Bros', img: 'media/buttons/mariobros.webp', embed: 'https://definitelynotblocked-three.vercel.app/games/supermariobros/index.html', external: true, listed: true },
  { slug: 'supersmashbros', title: 'Super Smash Bros', key: 'Super Smash Bros', label: 'Super Smash Bros', img: 'media/buttons/supersmashbros.jpg', embed: 'https://fvuiaosvhsfasjdfsagp.netlify.app/games/supersmashbros/', external: true, listed: true },
  { slug: 'taiseiproject', title: 'Taisei Project', key: 'Taisei Project', label: 'Taisei Project', img: 'media/buttons/taisei.png', embed: 'game-embeds/taiseiproject.html', external: false, listed: true },
  { slug: 'theycomin', title: 'They Are Coming', key: 'They Are Coming', label: 'They Are Coming', img: '', embed: 'game-embeds/theycomin.html', external: false, listed: false },
  { slug: 'tinyfishing', title: 'Tiny Fishing', key: 'Tiny Fishing', label: 'Tiny Fishing', img: 'media/buttons/tiny-fishing-square-icon.png', embed: 'game-embeds/tinyfishing.html', external: false, listed: true },
  { slug: 'ultrakill', title: 'Ultrakill', key: 'Ultrakill', label: 'Ultrakill', img: 'media/buttons/ultrakill.jpeg', embed: 'game-embeds/ultrakill.html', external: false, listed: true },
  { slug: 'unfairundyne', title: 'Unfair Undyne', key: 'Unfair Undyne', label: 'Unfair Undyne', img: 'media/buttons/Undyne_face.webp', embed: 'game-embeds/unfairundyne.html', external: false, listed: true },
  { slug: 'vex', title: 'Vex', key: 'Vex', label: 'Vex', img: 'media/buttons/vex.png', embed: 'game-embeds/vex.html', external: false, listed: true },
  { slug: 'vex2', title: 'Vex 2', key: 'Vex 2', label: 'Vex 2', img: 'media/buttons/vex2.jpeg', embed: 'game-embeds/vex2.html', external: false, listed: true },
  { slug: 'vex3', title: 'Vex 3', key: 'Vex 3', label: 'Vex 3', img: 'media/buttons/vex3.png', embed: 'game-embeds/vex3.html', external: false, listed: true },
  { slug: 'volleyrandom', title: 'Volley Random', key: 'Volley Random', label: 'Volley Random', img: 'media/buttons/volley.png', embed: 'game-embeds/volleyrandom.html', external: false, listed: true },
  { slug: 'yumenikki', title: 'Yume Nikki', key: 'Yume Nikki', label: 'Yume Nikki', img: 'media/buttons/yume-nikki.webp', embed: 'game-embeds/yume.html', external: false, listed: true },
];

export const listedGames = games.filter((g) => g.listed);

export function findGame(slug) {
  return games.find((g) => g.slug === slug);
}
